"""Testing utilities for miles_tito_tokenizers.

Derived from miles.utils.test_utils.
"""

from __future__ import annotations

from miles_tito_tokenizers.testing.chat_template_verify import (
    ALL_CASES,
    CaseSpec,
    THINKING_MODES,
    VerifyResult,
    check_coverage,
    enable_thinking_variants,
    run_all_checks,
    run_all_checks_via_tito,
    select_cases,
    simulate_pretokenized_path,
    verify_append_only,
    verify_append_only_via_tito,
    verify_append_only_via_tito_instance,
)
from miles_tito_tokenizers.testing.mock_trajectories import (
    ALL_TOOLS,
    DATE_TOOL,
    WEATHER_TOOLS,
    IntermediateSystemThinkingTrajectory,
    IntermediateSystemTrajectory,
    LongChainThinkingTrajectory,
    LongChainTrajectory,
    MultiRoleSequenceTrajectory,
    MultiToolSingleTurnTrajectory,
    MultiTurnNoToolThinkingTrajectory,
    MultiTurnNoToolTrajectory,
    MultiTurnThinkingTrajectory,
    MultiTurnTrajectory,
    MultiUserToolChainTrajectory,
    MultiUserTurnThinkingTrajectory,
    ParallelToolsTrajectory,
    ProcessFn,
    ProcessResult,
    RetrySystemTrajectory,
    SequentialProcessFn,
    SimpleNoToolTrajectory,
    SingleToolThinkingTrajectory,
    SingleToolTrajectory,
    Trajectory,
    Turn,
    build_process_fn,
    build_trajectory,
    last_user_index,
)

__all__ = [
    "ALL_CASES",
    "ALL_TOOLS",
    "DATE_TOOL",
    "WEATHER_TOOLS",
    "CaseSpec",
    "IntermediateSystemThinkingTrajectory",
    "IntermediateSystemTrajectory",
    "LongChainThinkingTrajectory",
    "LongChainTrajectory",
    "MultiRoleSequenceTrajectory",
    "MultiToolSingleTurnTrajectory",
    "MultiTurnNoToolThinkingTrajectory",
    "MultiTurnNoToolTrajectory",
    "MultiTurnThinkingTrajectory",
    "MultiTurnTrajectory",
    "MultiUserToolChainTrajectory",
    "MultiUserTurnThinkingTrajectory",
    "ParallelToolsTrajectory",
    "ProcessFn",
    "ProcessResult",
    "RetrySystemTrajectory",
    "SequentialProcessFn",
    "SimpleNoToolTrajectory",
    "SingleToolThinkingTrajectory",
    "SingleToolTrajectory",
    "THINKING_MODES",
    "Trajectory",
    "Turn",
    "VerifyResult",
    "build_process_fn",
    "build_trajectory",
    "check_coverage",
    "enable_thinking_variants",
    "last_user_index",
    "run_all_checks",
    "run_all_checks_via_tito",
    "select_cases",
    "simulate_pretokenized_path",
    "verify_append_only",
    "verify_append_only_via_tito",
    "verify_append_only_via_tito_instance",
]
